services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/postgres
    depends_on:
      - db
    networks:
      - network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_APP_BACKEND_ADDRESS=http://localhost/api
    depends_on:
      - backend
    networks:
      - network

volumes:
  postgres:

networks:
  network:
    driver: bridge

